job exception: local variable 'results_dict' referenced before assignment

Traceback (most recent call last):
  File "/storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce/hyperopt/tranvae_hyperparam_search.py", line 153, in <module>
    best = fmin(
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/fmin.py", line 507, in fmin
    return trials.fmin(
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/base.py", line 682, in fmin
    return fmin(
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/fmin.py", line 292, in run
    self.serial_evaluate()
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq/lib/python3.8/site-packages/hyperopt/base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "/storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce/hyperopt/tranvae_hyperparam_search.py", line 149, in objective
    'loss': -results_dict[cell_type_key[-1]]['report']['weighted avg']['f1-score'],
UnboundLocalError: local variable 'results_dict' referenced before assignment
